"""Render a structured review JSON into Greptile-style HTML for posting as a PR comment.

Usage:
  render.py <review.json>        # writes HTML to stdout
"""

from __future__ import annotations

import argparse
import html
import json
import re
import sys

BADGE_BASE = "https://greptile-static-assets.s3.amazonaws.com/badges"  # cra brand badges TBD


def esc(s: str | None) -> str:
    """Escape for use inside HTML *attributes* (alt=, href=, etc.)."""
    return html.escape(s or "", quote=True)


def md(s: str | None) -> str:
    """Body text destined for a GitHub PR comment — Markdown rendered, so pass through."""
    return s or ""


def render_diagram(mermaid: str | None, kind: str | None) -> str:
    if not mermaid:
        return ""
    # Strip stray fences if the model added them
    s = mermaid.strip()
    s = re.sub(r"^```mermaid\s*", "", s)
    s = re.sub(r"\s*```\s*$", "", s)
    label = "Sequence Diagram" if kind == "sequence" else "Flowchart" if kind == "flowchart" else "Diagram"
    return f"\n<h3>{esc(label)}</h3>\n\n```mermaid\n{s}\n```\n"


def render_issues(issues: list[dict]) -> str:
    if not issues:
        return ""
    lines = []
    for i in issues:
        label = md(i.get("label", ""))
        body = md(i.get("body", ""))
        prio = i.get("priority")
        prio_tag = f"[{md(prio)}] " if prio else ""
        lines.append(f"- {prio_tag}**{label}**: {body}")
    return "\n".join(lines) + "\n"


_FIX_EFFORT_TAG = {"quick": "⚡ Quick win", "moderate": "🔧 Moderate", "heavy": "🏗️ Heavy lift"}


def render_inline(comments: list[dict]) -> str:
    """Render full comments below the table (since we post one bulk summary)."""
    if not comments:
        return ""
    out = []
    for c in comments:
        prio = c.get("priority", "")
        prio_badge = f'<a href="#"><img alt="{esc(prio)}" src="{BADGE_BASE}/{esc(prio.lower())}.svg"></a> ' if prio else ""
        fix_effort = c.get("fix_effort")
        fix_tag = f" · _{_FIX_EFFORT_TAG[fix_effort]}_" if fix_effort in _FIX_EFFORT_TAG else ""
        f = md(c.get("file", ""))
        ls = c.get("line_start", "?")
        le = c.get("line_end", ls)
        rng = f"{ls}" if ls == le else f"{ls}-{le}"
        body = md(c.get("body", ""))
        sug = c.get("suggestion")
        sug_block = f"\n\n```suggestion\n{sug}\n```\n" if sug else ""
        out.append(f"**`{f}:{rng}`** — {prio_badge}{body}{fix_tag}{sug_block}\n")
    return "\n".join(out)


def render_security(findings: list[dict]) -> str:
    if not findings:
        return ""
    out = ["\n<details open><summary><h3>Security Review</h3></summary>\n"]
    for fi in findings:
        out.append(f"- **{md(fi.get('label',''))}** (`{md(fi.get('file',''))}`): {md(fi.get('body',''))}")
    out.append("\n</details>\n")
    return "\n".join(out)


_COMPLEXITY_LABEL = {1: "Trivial", 2: "Easy", 3: "Moderate", 4: "Complex", 5: "Heavy"}


def render(review: dict) -> str:
    summary = md(review.get("summary", ""))
    verdict = md(review.get("verdict", ""))
    conf = review.get("confidence")
    effort = review.get("effort_estimate") or {}
    issues = review.get("issues", []) or []
    comments = review.get("comments", []) or []
    sec = review.get("security_findings", []) or []
    diagram = review.get("diagram")
    diagram_kind = review.get("diagram_kind")
    files = review.get("changed_files_overview", []) or []

    parts = []
    parts.append("<h3>cra Summary</h3>\n")
    parts.append(f"{summary}\n")
    iss = render_issues(issues)
    if iss:
        parts.append("\n" + iss)
    if conf is not None:
        parts.append(f"\n<h3>Confidence: {conf}/5</h3>\n")
    if verdict:
        parts.append(f"\n{verdict}\n")
    if effort:
        cx = effort.get("complexity")
        mins = effort.get("minutes")
        label = _COMPLEXITY_LABEL.get(cx, "?") if cx else "?"
        if cx and mins:
            parts.append(f"\n**Estimated review effort:** 🎯 {cx} ({label}) · ⏱️ ~{mins} minutes\n")
    if files:
        parts.append("\n<h3>Important Files Changed</h3>\n\n| File | Overview |\n|---|---|\n")
        for f in files:
            parts.append(f"| `{md(f.get('path',''))}` | {md(f.get('overview',''))} |\n")
    if comments:
        parts.append("\n<h3>Inline Comments</h3>\n\n")
        parts.append(render_inline(comments))
    parts.append(render_diagram(diagram, diagram_kind))
    parts.append(render_security(sec))
    parts.append('\n<!-- cra_review -->\n')
    parts.append(f'<sub>Generated by <a href="https://github.com/kendreaditya/cra">cra</a> · confidence {conf if conf is not None else "?"}/5</sub>\n')
    return "".join(parts)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("review_json", help="path to a structured review JSON file")
    args = p.parse_args()
    with open(args.review_json) as f:
        review = json.load(f)
    print(render(review))


if __name__ == "__main__":
    main()
